### ISSUE TITLE
[Feature request] Controller compatibility with Applied Energistics 2 Storage Bus

### ISSUE THREAD

**Issue by AndreAugustoDev** [P3pp3rF1y/SophisticatedStorage#240]
I have a controller connected to limited barrels and connected to the controller an AE2 storage bus.

Currently, when I try to make a recipe that uses the workbench, it works.
But when I try to make a recipe that uses an external process, e.g. a mekanism furnace, i can't complete the recipe because it shows i have no ingredient even if i have it stored

The same setup using Functional Storage drawers allows me to make recipes with an external process

**Comment by P3pp3rF1y** [comment]
it is already compatible so this must be some kind of bug. Does it show the ingredients in AE when you look into the terminal? I have also fixed some bugs with locking recently so make sure you are running on the latest version and let me know if that fixed it.

**Comment by AndreAugustoDev** [comment]
So maybe it's a bug
I can normally see the items in the terminal, both with locked and unlocked barrels
And make basic recipes too (3x3)

These are the versions used:
`Sophisticated Core 1.19.2-0.5.78.363`
`Sophisticated Storage 1.19.2-0.8.36.543`
`Sophisticated Backpacks 1.19.2-3.18.54.881` if useful to know

Log https://mclo.gs/z08gxqI

<details>
<summary>Some screenshots</summary>

![2023-07-10_10 21 11](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/25272842/70d7970e-af3f-47de-a600-cc1eb4e0e270)
![2023-07-10_10 21 21](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/25272842/7350bd3e-147b-40cf-be93-177b9cc9c933)
![2023-07-10_10 21 31](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/25272842/11346ebe-953b-4e38-aa46-923022df3443)
![2023-07-10_10 21 50](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/25272842/e552685f-9bb9-4d14-b82b-9aba346ccc2d)
![2023-07-10_10 22 03](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/25272842/ee25df2b-f609-46ea-8d00-b8e6160e6ba1)
![2023-07-10_10 22 18](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/25272842/a096987c-82f4-4fbc-9473-6b82128914c5)

</details>

**Comment by P3pp3rF1y** [comment]
Just tried recreating in the pack that I play which has the latest versions (same ones you have here) and with AE + both vanilla and mekansim furnace (smelter) it just works so I don't understand why it doesn't work for you.

The only thought I have here is that perhaps you had a filter upgrade in the barrel and somehow the cache got corrupted there basically behaving as if it wasn't possible to take out of the barrel

**Comment by AndreAugustoDev** [comment]
I still haven't been able to find what is causing this problem
Even some disabled mods made no difference

Testing in a super flat void world, I see that it works without the compreession upgrade, but not with it.
In my survival world it still doesn't work

Is there any way to fix the possibly corrupted cache?

**Comment by P3pp3rF1y** [comment]
I fixed one caching issue with locking storages yesterday so I would suggest trying with that new version again and see whether it will work. I have just tested with both locked and unlocked barrel with compression upgrade inside and still works for me with the latest version.

**Comment by P3pp3rF1y** [comment]
And actually to answer the caching issue, normally that can be solved by breaking and replacing barrel + upgrades + items.

**Comment by AndreAugustoDev** [comment]
I think it has something to do with how the compression upgrade works
I did a test again with a basic AE2 setup + mekanism furnace + controller with a limited barrel in a new world
Item in barrel without upgrade was usable
But when I put the compression upgrade, the item is shown in the terminal, but when trying to make the recipe in the furnace the item is shown as missing
Removing the upgrade makes it work

**Comment by P3pp3rF1y** [comment]
well this is the exact same test that I did earlier (and just retried now with a few additional tries in different order) in TNP limitless 6 modpack which has a ton of other mods and it just works without any issues. 

The only thing i can think of is some weirdness going on with compression recipes in your case. Are you actually able to pull the coal out of terminal when it shows as missing in the recipe?

**Comment by P3pp3rF1y** [comment]
closing given no additional steps were provided in quite a while
